language: rust
os:
  - linux
  - osx
rust:
  - stable
  - beta
  - nightly
script:
  # With std.
  - cargo test -vv
  # Without std.
  - cargo test -vv --no-default-features
  # With std, and linking against the "sse" implementation.
  - cargo test -vv --all-features
